version: "3"
services:
  ofelia:
    image: mcuadros/ofelia:latest
    restart: always
    command: daemon --docker
    depends_on: 
      - puppeteer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels: 
      ofelia.job-run.yiqingtong.container: "yiqingtong_puppeteer"
      ofelia.job-run.yiqingtong.schedule: "0 15 16 * * *"      
      # ofelia.job-run.checkup.container: "yiqingtong_puppeteer"
      # ofelia.job-run.checkup.schedule: "0 15 9,13,18 * * *"
    environment:
      - TZ=Asia/Shanghai

  puppeteer:
    image: chenseanxy/yiqingtong-puppeteer:latest
    container_name: "yiqingtong_puppeteer"
    restart: "no"
    volumes:
      - ./screens:/usr/src/app/screens
    env_file: 
      - .env
